// One-off generator: bakes seamlessly-tileable cell geometry into src/lib/tiles.ts
// Run: node scripts/gen-tiles.mjs   (d3-delaunay is a devDependency, not shipped)
import { Delaunay } from 'd3-delaunay';
import { writeFileSync } from 'node:fs';

const S = 200; // tile size

// deterministic PRNG so output is stable across runs
function rng(seed) {
  let s = seed >>> 0;
  return () => (((s = (s * 1664525 + 1013904223) >>> 0) / 4294967296));
}

// Poisson-ish sampling on a torus, then Lloyd relaxation -> even, organic cells
function torusPoints(n, seed, relax = 6) {
  const r = rng(seed);
  let pts = Array.from({ length: n }, () => [r() * S, r() * S]);
  for (let it = 0; it < relax; it++) {
    // replicate into 3x3 so cells wrap
    const all = [];
    for (let dx = -1; dx <= 1; dx++)
      for (let dy = -1; dy <= 1; dy++)
        for (const [x, y] of pts) all.push([x + dx * S, y + dy * S]);
    const d = Delaunay.from(all);
    const v = d.voronoi([-S, -S, 2 * S, 2 * S]);
    const next = [];
    for (let i = 0; i < pts.length; i++) {
      // index of the centre copy (dx=0,dy=0 is the 5th block => offset 4*n)
      const cell = v.cellPolygon(4 * pts.length + i);
      if (!cell) { next.push(pts[i]); continue; }
      let a = 0, cx = 0, cy = 0;
      for (let j = 0; j < cell.length - 1; j++) {
        const [x0, y0] = cell[j], [x1, y1] = cell[j + 1];
        const f = x0 * y1 - x1 * y0;
        a += f; cx += (x0 + x1) * f; cy += (y0 + y1) * f;
      }
      a *= 0.5;
      if (!a) { next.push(pts[i]); continue; }
      next.push([((cx / (6 * a)) % S + S) % S, ((cy / (6 * a)) % S + S) % S]);
    }
    pts = next;
  }
  return pts;
}

// Build the wrapped voronoi and emit each centre cell as a closed path,
// inset toward its centroid so the gaps read as "webbing" between cells.
function cellPaths(n, seed, inset, relax) {
  const pts = torusPoints(n, seed, relax);
  const all = [];
  for (let dx = -1; dx <= 1; dx++)
    for (let dy = -1; dy <= 1; dy++)
      for (const [x, y] of pts) all.push([x + dx * S, y + dy * S]);
  const d = Delaunay.from(all);
  const v = d.voronoi([-S, -S, 2 * S, 2 * S]);
  const out = [];
  // emit the centre block AND its 8 neighbours clipped by the tile, so the
  // pattern is continuous across tile edges in every direction
  for (let b = 0; b < 9; b++) {
    for (let i = 0; i < pts.length; i++) {
      const cell = v.cellPolygon(b * pts.length + i);
      if (!cell) continue;
      const ring = cell.slice(0, -1);
      let cx = 0, cy = 0;
      for (const [x, y] of ring) { cx += x; cy += y; }
      cx /= ring.length; cy /= ring.length;
      // skip cells entirely outside the tile (+margin)
      if (cx < -30 || cx > S + 30 || cy < -30 || cy > S + 30) continue;
      const pulled = ring.map(([x, y]) => {
        const vx = x - cx, vy = y - cy;
        const L = Math.hypot(vx, vy) || 1;
        const k = Math.max(0, (L - inset)) / L;
        return [cx + vx * k, cy + vy * k];
      });
      out.push('M' + pulled.map(([x, y]) => `${x.toFixed(1)} ${y.toFixed(1)}`).join('L') + 'Z');
    }
  }
  return out;
}

const tiles = {
  // large organic cells — the hero "Fracture" look
  voronoiCoarse: cellPaths(14, 20240115, 3.2, 8),
  // tighter cells — "Volt" crackle
  voronoiFine: cellPaths(34, 77003, 2.2, 8),
  // barely-relaxed = angular shards — "Magma"
  voronoiShard: cellPaths(20, 5150, 2.6, 1),
};

const ts = `// GENERATED by scripts/gen-tiles.mjs — do not edit by hand.
// Seamlessly tileable Voronoi cell geometry (200x200 tile, torus-wrapped +
// Lloyd-relaxed) used by the grip pattern system in src/lib/patterns.tsx.
export const TILE = 200;

${Object.entries(tiles)
  .map(([k, v]) => `export const ${k}: readonly string[] = ${JSON.stringify(v, null, 0)};`)
  .join('\n\n')}
`;

writeFileSync(new URL('../src/lib/tiles.ts', import.meta.url), ts);
console.log(Object.entries(tiles).map(([k, v]) => `${k}: ${v.length} cells`).join('\n'));
console.log('bytes:', ts.length);
