// GENERATED by scripts/scan-media.mjs — run `npm run media:scan` after
// adding or removing files in public/products/. Do not edit by hand.
import type { MediaAsset } from "@/data/media";

export const GENERATED_MEDIA: Record<string, MediaAsset[]> = {
  "dark-matter|*": [
    {
      "src": "/products/dark-matter.png",
      "w": 1120,
      "h": 860,
      "kind": "front",
      "alt": "Dark Matter Grips fitted to a controller"
    }
  ],
  "ember|*": [
    {
      "src": "/products/ember.png",
      "w": 1120,
      "h": 860,
      "kind": "front",
      "alt": "Ember Grips fitted to a controller"
    }
  ],
  "ice-froyo|*": [
    {
      "src": "/products/ice-froyo.png",
      "w": 1120,
      "h": 860,
      "kind": "front",
      "alt": "Ice Froyo Grips fitted to a controller"
    }
  ],
  "vapor|*": [
    {
      "src": "/products/vapor.png",
      "w": 1120,
      "h": 860,
      "kind": "front",
      "alt": "Vapor Grips fitted to a controller"
    }
  ],
  "venom|*": [
    {
      "src": "/products/venom.png",
      "w": 1120,
      "h": 860,
      "kind": "front",
      "alt": "Venom Grips fitted to a controller"
    }
  ],
  "volt|*": [
    {
      "src": "/products/volt.png",
      "w": 1120,
      "h": 860,
      "kind": "front",
      "alt": "Volt Grips fitted to a controller"
    }
  ]
};
